env:
  CI_ALLOW_ROOT: '1'
  CI_CONFIG: ./ci/generate.nix
  CI_PLATFORM: gh-actions
jobs:
  ci:
    name: base16-schemes-json-generate
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: generate
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4-broken
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@nix2.4-broken
      with:
        attrs: ci.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@nix2.4-broken
      with:
        attrs: ci.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@nix2.4-broken
      with:
        attrs: ci.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@nix2.4-broken
      with:
        attrs: ci.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  ci-check:
    name: base16-schemes-json-generate check
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: generate
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@nix2.4-broken
    - id: ci-action-build
      name: nix build ci.gh-actions.configFile
      uses: arcnmx/ci/actions/nix/build@nix2.4-broken
      with:
        attrs: ci.gh-actions.configFile
        out-link: .ci/workflow.yml
    - id: ci-action-compare
      name: gh-actions compare
      uses: arcnmx/ci/actions/nix/run@nix2.4-broken
      with:
        args: -u .github/workflows/base16-schemes-json-generate.yml .ci/workflow.yml
        attrs: nixpkgs.diffutils
        command: diff
name: base16-schemes-json-generate
'on':
  pull_request:
    branches:
    - generate
  push:
    branches:
    - generate
  schedule:
  - cron: 0 0 * * *
